In [2]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3])
print(arr)

# Create a 2D array (matrix)
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

# Array of zeros
#2 rows 3 columns
zeros = np.zeros((2, 3))
print(zeros)

# Array of random numbers
# 3 rows 3 columns
rand = np.random.rand(3, 3)
print(rand)


[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.13616913 0.70650773 0.11965514]
 [0.88914098 0.32589474 0.58107293]
 [0.78440175 0.69059543 0.58334215]]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)      # element-wise add
print(a * b)      # element-wise multiply
# If a and b are two vectors:
# a = (a1, a2, a3)
# b = (b1, b2, b3)
# Then the dot product a · b is:
# a · b = a1 * b1 + a2 * b2 + a3 * b3. 
print(a.dot(b))   # dot product


[5 7 9]
[ 4 10 18]
32


In [11]:
scores=np.random.randint(1,11,(3,3))
print(scores)
maxi=-1
index=(-1,-1)
sum=0
for row_ind,r in enumerate(scores):# will have rows of the multidimensional array
    for col_ind,c in enumerate(r):# will iterate through elements in each row
        sum+=c;
        if (c>maxi):
            maxi=c
            index=(row_ind,col_ind)
mean=sum/scores.size
print(sum)
print(mean)
print(maxi)
print(index)

[[4 4 5]
 [7 4 7]
 [3 4 1]]
39
4.333333333333333
7
(1, 0)


In [12]:
import numpy as np

scores = np.random.randint(1, 11, (3, 3))
print(scores)

total_sum = scores.sum()
mean = scores.mean()
max_val = scores.max()
max_pos = np.unravel_index(np.argmax(scores), scores.shape)

print("Sum:", total_sum)
print("Mean:", mean)
print("Max value:", max_val, "at position", max_pos)


[[9 4 9]
 [4 6 7]
 [9 6 2]]
Sum: 56
Mean: 6.222222222222222
Max value: 9 at position (np.int64(0), np.int64(0))
